### ISSUE TITLE
Powergraph labels

### ISSUE THREAD

**Issue by aassie** [AuReMe/metage2metabo#12]
Hello, me again,

I have a couple of questions about the m2m_analysis workflow.

1. Would it be possible to change the taxonomy level of the stat summary steps? The class level is not really informative for what I am looking at and I was wondering if it could be changed to any lower level

2. I was looking at the powergraph output from the m2m pipeline and it seems that at some point my bacteria names got changed to their taxonomies but I can't find how to link their changed names to the original. Is there a way to keep the original name in the figure?

Example below:

![Meme2](https://user-images.githubusercontent.com/14992488/102511382-56092a00-404e-11eb-83ef-654888f32639.png)

**Comment by cfrioux** [comment]
Hello Adrien,

I'll try to answer to both of your questions. So far m2m_analysis is not as flexible as it could be as it was implemented mainly in order to reproduce the figures from our manuscript.

1 - By default we look at the phylum and no other taxonomic level. We might modify that in the near future. I know that @ArnaudBelcour  intends to work again on `m2m_analysis` over the next few weeks. In the meantime should you want to look at the genus-level for instance, you could modify the code [in this function](https://github.com/AuReMe/metage2metabo/blob/4c42552da163dff00e45ab611cbd9df50ac65318/metage2metabo/m2m_analysis.py#L301), and in particular L315 which is where we retrieve the first four characters of phylum for counting. If you change `rank[0]` for  `rank[4]`, you will calculate your stats at the genus level.

2 - Indeed we introduced a mapping step in the code in order to prevent long names to decrease readability in the figure. The matching between the new names and the original ones is given in `output_dir/taxon_phylum.tsv`. If you do not want such mapping to be done, you can rerun the analysis without the `--taxon taxon_id.tsv` argument. See the attached figures that were generated with and without the `--taxon` argument.
![targets_toy bb_wtaxl](https://user-images.githubusercontent.com/9773817/102618606-63501280-413b-11eb-905b-cbce5202fbe1.png)
![targets_toy](https://user-images.githubusercontent.com/9773817/102618609-64813f80-413b-11eb-9958-291bed561381.png)

I hope this helps, please let me know if this is unclear.

**Comment by aassie** [comment]
Thank you very much for your replies! 

Sorry about 2) that I missed that file in my output directory!

**Comment by cfrioux** [comment]
No worries, we will clarify the documentation.
