### ISSUE TITLE
New GenBank file format

### ISSUE THREAD

**Issue by KDeaton** [AuReMe/metage2metabo#16]
GenBank has changed the file format from .gbk to .gbff
"*_genomic.gbff.gz (Genomic GenBank format)
GenBank flat file format of the genomic sequence(s) in the assembly. This file includes both the genomic sequence and the CONTIG description (for CON records), hence, it replaces both the .gbk .gbs format files that were provided in the old genomes FTP directories." 
[https://www.ncbi.nlm.nih.gov/genome/doc/ftpfaq/#files](url)

Recon won't run with the new file format. Suggestions?

**Comment by ArnaudBelcour** [comment]
Hi @KDeaton,

The ``.gbff`` file format is handled by Pathway Tools (the tools used by ``m2m recon`` to reconstruct draft metabolic network). And mpwt (the package used by m2m to launch multiples processes of Pathway Tools) handles this format since its [version 0.5.4](https://github.com/AuReMe/mpwt/releases/tag/v0.5.4).

So there should be no problem by using this file format with ``m2m recon``. If you encounter an issue please give us a feedback.

But the doc is not clear about this. I have updated it in 740bb0f7917bfbec93f7e926f5d4dfd2282815ff and it should clarify the message.

Thank you for the issue.
