### ISSUE TITLE
m2m recon not working with gbff file inputs

### ISSUE THREAD

**Issue by alsmadin01** [AuReMe/metage2metabo#43]
Hi @ArnaudBelcour,

I am trying to use .gbff files downloaded from NCBI for metabolic reconstruction using Pathway Tools (m2m recon). However, I am obtaining the error attached. Please note that m2m recon works for me when using .gbk files as input.

<img width="1440" alt="Screen Shot 2022-09-29 at 8 51 49 PM" src="https://user-images.githubusercontent.com/102759083/193167363-ad819e53-d66b-4747-bc70-975f31b8d9d7.png">

Thank you.

Best regards,

Noor Alsmadi

**Comment by ArnaudBelcour** [comment]
Hi @alsmadin01,

The error associated with your log is due to mpwt not showing correctly that the run of PathoLogic on `DEUA01000019` has failed. I have fixed this in mpwt version [0.8.1](https://github.com/AuReMe/mpwt/releases/tag/0.8.1). By updating to this version, mpwt should show that there is an error with this genome.

And indeed, the gbff associated with this genome and the corresponding genome on the NCBI ([DEUA01000019](https://www.ncbi.nlm.nih.gov/nuccore/DEUA01000019/)) do not contain any genes or proteins. So Pathway Tools can not predict metabolic networks from these data as it does not perform annotation of the genomes.
So you have to predict the genes and the functional annotation of these genes for this genome with annotation tools (such as [prokka](https://github.com/tseemann/prokka) or [bakta](https://github.com/oschwengers/bakta)).

Best regards,
Arnaud Belcour.

**Comment by cfrioux** [comment]
You can do it with `m2m seeds` ([doc](main_seeds)) that will create a seed SBML file from a simple file with a list of nutrients identifiers (the way they look in the SBML file of your reconstructed metabolic networks, i.e with their compartment). 
A few remarks on that:
- You still need to turn your medium content into a list of IDs matching the database you use (e.g. metacyc). This is unfortunately manual
- I advise that you put the cytosol compartment for the seeds so that the absence of transport reactions due to the automatic reconstruction does not impede the simulations.
- You might also test adding a few cofactors (M_ADP_c, M_NAD_c, M_NADP_c in Metacyc) to prevent any missing activated functions due to the incomplete activation of cycles (once again, because of the automatic reconstruction).

**Comment by cfrioux** [comment]
I'll close this issue now. Reopen it if needed.
