### ISSUE TITLE
How to prepare inputs for metage2metabo

### ISSUE THREAD

**Issue by LiZhihua1982** [AuReMe/metage2metabo#51]
In the documents, https://metage2metabo.readthedocs.io/en/latest/input.html.  The genomes are expected to be in GenBank format (.gbk or .gbff), I want to know which software and parameters are suitable for produce these input file, because I try several softwares, it report errors. In addition, the metabolic networks must be in SBML format, I also want to know the detail procedure to abtain this sbml file, using CarveMe,ModelSEED or gapseq? Thank you very much!

**Comment by cfrioux** [comment]
Hi,

### Genbank format

If you use reference genomes, e.g. from the NCBI, you can download genbank files directly on the database. Be sure to pick ones that contain annotations, or otherwise reannotate them.
Prokka is an annotation tool that provides genbank files. 
Otherwise, if you use genomes that you annotated with Eggnog-mapper, you might want to take a look to [emapper2gbk](https://github.com/AuReMe/emapper2gbk).

### SBML format

The format is very usual in metabolic modelling. Carveme, gapseq and ModelSEED will provide SBMLs.

**Comment by LiZhihua1982** [comment]
Dear Prof.Clémence Frioux,
    Thank you very much for your explain! For example, I have several MAGs, I want to analyze them using metage2metabo, first I need prepare gdb file using prokka, which I found it will report error when direct using prokka, it need revise the taxid and LOCUS line, this will need a large time when many MAGs need to be revised. second, I need prepare the seed file. If possible, would you take the MAGs as input file directly. Thanks again!

Best regards

Li Zhihua

________________________________
发件人: Clémence Frioux ***@***.***>
发送时间: 2023年8月21日 14:15
收件人: AuReMe/metage2metabo ***@***.***>
抄送: Li Zhihua ***@***.***>; Author ***@***.***>
主题: Re: [AuReMe/metage2metabo] How to prepare inputs for metage2metabo (Issue #51)


Hi,

Genbank format

If you use reference genomes, e.g. from the NCBI, you can download genbank files directly on the database. Be sure to pick ones that contain annotations, or otherwise reannotate them.
Prokka is an annotation tool that provides genbank files.
Otherwise, if you use genomes that you annotated with Eggnog-mapper, you might want to take a look to emapper2gbk<https://github.com/AuReMe/emapper2gbk>.

SBML format

The format is very usual in metabolic modelling. Carveme, gapseq and ModelSEED will provide SBMLs.

―
