### ISSUE TITLE
M2M workflow and mincom

### ISSUE THREAD

**Issue by ggmirandac** [AuReMe/metage2metabo#64]
Hi,

I have been working with m2m to do some microbial community metabolic interaction analysis and I have stumble with and issue. When trying to run the mincom minimal_community.mincom() function of the python API the target the mincom.json is often empty in the fields that are not the producible metabolites. 

I am wondering if this is because of the way that the target.sbml file is created (I am using the main_seeds() function of m2m.__main__).

Otherwise, in the **m2m workflow** the optional argumen -t can be left empty and the addvalue metabolites are used. Is there a way to do the same with the python API?

Looking forward for your answer.

**Comment by ArnaudBelcour** [comment]
Hi @ggmirandac,

This could come from several issues. Are the metabolites present in the `target.sbml` file contained inside the metabolic networks of your organisms? Especially, are there no added or missing characters compared to the metabolite IDs in the sbml file?

For an in-depth exploration of this issue, is it possible that you share the `target.sbml` and the `mincom.json` files?

> Otherwise, in the m2m workflow the optional argumen -t can be left empty and the addvalue metabolites are used. Is there a way to do the same with the python API?

This behaviour can be achieved with a call to the [metacom_analysis](https://github.com/AuReMe/metage2metabo/blob/main/metage2metabo/m2m/m2m_workflow.py#L59) function. If you do not specify the `targets_file` argument of this function, it will compute the addedvalue metabolites and then use them as targets. And if you set `target_com_scope` to True, it will use the community scope as the targets instead of the addedvalue metabolites.

Best regards,
Arnaud Belcour.

**Comment by ggmirandac** [comment]
Hi, 
Thanks for the answer, but I manage to go throught by using the terminal command.
